# Docs: https://docs.cortex.io/docs/reference/basics/entities#service-entities

openapi: 3.0.0
info:
  title: vault-client
  description: >
    Go Client for Vault
  x-cortex-type: service
  x-cortex-slack:
    channels:
      - name: fnd-star-alerts
        notificationsEnabled: true
      - name: star-oncall
        notificationsEnabled: false
      - name: star-support
        notificationsEnabled: false
  x-cortex-owners:
    - type: group
      name: fnd-star
      provider: CORTEX
  x-cortex-tag: vault-client
  x-cortex-git:
    github:
      repository: getoutreach/vault-client
  x-cortex-oncall:
    pagerduty:
      id: P21C0GV
      type: SERVICE
  x-cortex-link:
    ## These are useful documentation links for this service. Please fill in the customLinks block if you have additional documentation links.
    ## name: The name of the link
    ## type: Choose one type from (dashboard,documentation,healthcheck,logs,metrics,runbook)
    ## url: The link url
    ## description(optional): Description to this link
    - name: API Docs
      type: api_documentation
      url: https://engdocs.outreach.cloud/github.com/getoutreach/vault-client#section-readme
    ## <<Stencil::Block(customLinks)>>
    ## <</Stencil::Block>>
  x-cortex-custom-metadata:
    app: vault-client
    name: vault-client
    repo: https://github.com/getoutreach/vault-client
    framework: stencil
    language: Golang
    stencil_version: v1.38.1
    golang_version: 1.22.0
    cli: false
    service: false
    product: Outreach
    lifecycle: in_development
    ## <<Stencil::Block(extraAliases)>>
    ## <</Stencil::Block>>
    reporting_team: fnd-star
    lintroller: platinum
  x-cortex-groups:
    - lifecycle: in_development
    - product: Outreach
    - language: Golang
    - framework: stencil
    - engOrg: fnd
