name: vault-client
reportingTeam: fnd-star
description: Go Client for Vault
oss: true
slack: star-notifications
library: true
circleAPIKey: ""
lintroller: platinum
tracing: honeycomb
metrics: datadog
releaseType: ""
deployTo:
  environments: []
arguments:
  circleAPIKey: ""
  commands: []
  commitGuard: false
  dependencies:
    optional: []
    required: []
  description: Go Client for Vault
  grpcClients: []
  kubernetes:
    groups: []
  lintroller: platinum
  metrics: datadog
  opslevel:
    confluenceSpaceKey: STAR
    datadogDashboards:
      mainLink: ""
    designDocumentLink: ""
  oss: true
  releaseOptions:
    allowMajorVersions: false
    enablePrereleases: false
  reportingTeam: fnd-star
  resources: {}
  service: false
  slack: star-notifications
  terraform:
    datadog:
      grpc:
        evaluationWindow: ""
        latency:
          percentiles:
            highTraffic: 0
            lowTraffic: 0
          thresholds:
            highTraffic: 0
            lowTraffic: 0
        lowTrafficCountThreshold: 0
        qos:
          thresholds:
            highTraffic: 0
            lowTraffic: 0
        tags: []
      http:
        evaluationWindow: ""
        percentiles:
          highTraffic: 0
          lowTraffic: 0
        thresholds:
          highTraffic: 0
          lowCount: 0
          lowTraffic: 0
      pods:
        thresholds:
          availableLowCount: 0
  tracing: honeycomb
  tutorial: false
  vaultSecrets:
    - deploy/honeycomb_new/%(environment)s/honeycomb
    - deploy/launchdarkly/%(environment)s/launchdarkly
    - deploy/mint/%(environment)s/validation/mint-validator-payload
    - deploy/flagship-shared-secret/%(environment)s/authn-flagship-payload
modules:
  - name: github.com/getoutreach/stencil-outreach
  - name: github.com/getoutreach/stencil-circleci
  - name: github.com/getoutreach/stencil-actions
  - name: github.com/getoutreach/stencil-base
  - name: github.com/getoutreach/stencil-golang
opsLevel:
  serviceTier: 0
  lifecycle: ""
  confluenceSpaceKey: STAR
  pagerDutyLink: ""
  datadogDashboards:
    mainLink: ""
    custom: []
  designDocumentLink: ""
