name: vault-client
arguments:
  description: Go Client for Vault
  lintroller: platinum
  oss: true
  reportingTeam: fnd-pc
  service: false
  slack: pc-notifications
  ciOptions:
    skipDocker: true
    skipE2e: true
  vaultSecrets:
    - deploy/honeycomb_new/%(environment)s/honeycomb
    - deploy/launchdarkly/%(environment)s/launchdarkly
    - deploy/mint/%(environment)s/validation/mint-validator-payload
    - deploy/flagship-shared-secret/%(environment)s/authn-flagship-payload
modules:
  - name: github.com/getoutreach/stencil-outreach
  - name: github.com/getoutreach/stencil-circleci
  - name: github.com/getoutreach/stencil-actions
  - name: github.com/getoutreach/stencil-discovery
  - name: github.com/getoutreach/stencil-base
  - name: github.com/getoutreach/stencil-golang
